version: "3.2"

services:
  dev:
    stdin_open: true
    tty: true
    container_name: node-template
    image: paritytech/ci-linux:production
    working_dir: /var/www/node-template
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/node-template/.cargo
      - WASM_BUILD_TOOLCHAIN=nightly
    volumes:
      - .:/var/www/node-template
      - type: bind
        source: ./.local
        target: /root/.local
#   command: bash -c "rustup default nightly; cargo build --release && ./target/release/node-template --dev --ws-external"
    command: bash -c "rustup default stable; cargo build --release && ./target/release/node-template --dev --ws-external"
